version: '3'

networks:
  main-network:

services:
  #node
  node-service:
    build: ./backend
    container_name: node-container
    command: npm run watch_dev
    tty: true
    stdin_open: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./backend:/var/www/project
    networks:
      - main-network

  #redis
  redis-service:
    image: redis:6.2.5
    container_name: redis-container
    networks:
      - main-network
    volumes:
      - ./backend/redis/data:/data
      - ./backend/redis/redis.conf:/usr/local/etc/redis/redis.conf